version: '3.1'

services:
  bot:
    build: .
    environment:
      MONGODB: mongodb://<имя>:<пароль>@mongo:27017/
      TELEGRAM_TOKEN: <токен>
  mongo:
    image: mongo:4.4.29
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: <имя>
      MONGO_INITDB_ROOT_PASSWORD: <пароль>

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <имя>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <пароль>
      ME_CONFIG_MONGODB_URL: mongodb://<имя>:<пароль>@mongo:27017/
